fullstorydev/fullstory-browser-sdk

- README.md
We're no longer using named exports, and the example in the readme needs to be updated.
> updating readme to reflect changes to default module export

- .gitignore
- src/index.js
- src/snippet.js
- test/index.js
I've refactored the parameterized function signature for `FullStory.init` to use an options argument. This also applies to the `snippet` function as well.
Additional changes:
- added `_fs_script` to snippet - this reflects the latest change to the snippet made by the RiR team
- removed the `fs` prefix from snippet option key names
- throwing an error if `orgId` is not provided as a snippet option and added a test
- updated tests; now cleaning up the `window` object before each test to return to pre-initialized state
> Using snippet options object for FullStory.init

- .circleci/config.yml
- README.md
- package.json
This is a simple three job workflow:
Build & Test --> Hold --> Deploy to NPM
Here's a sample pipeline on a test project: https://circleci.com/workflow-run/5bf54a02-19eb-4d7e-b58e-c3510969586b
> adding hold and deploy steps to CI workflow

- .github/actions/sync-snippet-action/main.js
While I was developing the GitHub Action that checks for the latest version of the snippet, I was using a workflow triggered by a `push`, which allowed me to test my code changes immediately: I'd change code, `push` it to the repo, trigger the action, and verify the results (on a forked repo).
I was using a `context` object from the `github` package to get access to information about the currently executing repository and branch. However, when I switched from a `push` trigger to a `schedule` trigger, the `context` object changed and the properties I relied on were not available.
This PR replaces the `context` object with references to stable [environment variables](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environmen …
> Remove github action context

- .github/actions/sync-snippet-action/main.js
- package-lock.json
I'm replacing the md5 hash used to check for differences between the local and remote snippet files with sha256 - per feedback from the FullStory security team.
This PR also includes a patch for a moderate-severity `npm audit` check
> updating md5 hash to sha256 hash when checking if snippet file content has changed

- .github/workflows/main.yml
The production `/code/v1/snippet` endpoint is live! this PR updates the GitHub Action to poll the prod endpoint.
> updating the SNIPPET_ENDPOINT env var to point to the prod snippet API

- .github/actions/sync-snippet-action/main.js
GitHub support got back to me with a cause and work-around for an issue where we can't merge PRs created by the GitHub Action. This PR implements the work-around. More details about the bug from GH support:
> The cause of the issue here is a bit obscure, and fundamentally a bug on our end. We're already working on a long-term fix in the product, but in the meantime, I've included an explanation and workaround below.
> It turns out that the base ref specified in the pull request created by GitHub Actions is refs/heads/master. A typical, user-created pull request would have instead specified a base ref of just master.
> The fully qualified base ref provided by GitHub Actions is equivalent to master in most contexts, but for one issue: it prevents our protected branch checks from locating …
> hard-coding base value when creating PR per GitHub support recommendation

- README.md
- package.json
- src/index.js
- test/index.js
Sentry is working on building a TypeScript integration with `@fullstorydev/browser` and discovered an inconsistency in the way we export functions. We `default export` an object in the JavaScript source code, but our typings file exports functions individually (no `default`). This PR changes the JavaScript source code to use named exports, which is consistent with how functions are defined in `index.d.ts`.
This is related to https://github.com/fullstorydev/fullstory-browser-sdk/issues/34
> Use named exports 

- package-lock.json
- package.json
- rollup.config.js
I hadn't yet configure CircleCI to run CI builds on forks when you created your PR. This is my attempt to trigger a build so the checks will pass.
> Added CommonJS bundle

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/index.d.ts
- src/index.js
- test/index.js
This PR fixes #1 and adds control over the snippet's iFrame recording options as seen in [Can FullStory capture content that is presented in iframes](https://help.fullstory.com/hc/en-us/articles/360020622514-Can-FullStory-capture-content-that-is-presented-in-iframes-).
> Adds iframe options to SDK

- README.md
This formats the Readme so that config options are more readable on NPM.
> updating readme to show init config options as a list

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
This PR:
- Adds the `devMode` flag re-using the environment properties available when using the Angular CLI
- Spell check corrections
> Angular devMode example

- README.md
Added a code snippet on how a developer would initialize the FullStory SDK on a Vue Js app, This is also adding the SDK to the [Vue instance property](https://vuejs.org/v2/cookbook/adding-instance-properties.html#Base-Example) which will allow other Vue instances to have access to that property. 
Example calling an event from another Vue component would look like this.  
```
this.$FullStory.event("Subscribed", {
uid_str: "750948353",
plan_name_str: "Professional",
plan_price_real: 299,
plan_users_int: 10,
days_in_trial_int: 42,
feature_packs: ["MAPS", "DEV", "DATA"]
});
```
> Added a code snippet for Vue

- package-lock.json
- package.json
I don't understand yet why the build is Red - Circle CI has the last several builds as Green
> bump to 1.4.9 to get a green build

- package-lock.json
- package.json
This pull request updates several packages (log4j, mocha, engine.io, follow-redirects) which had been failing the `npm audit` security checks.
> resolve security audit check

- README.md
- src/index.d.ts
- src/index.js
This pull request exposes a new method `setVars` on the package interface. With the FS.setVars API, you can send your own custom page names and properties to FullStory. Read more about it at [help.fullstory.com](https://help.fullstory.com/hc/en-us/articles/1500004101581-FS-setVars-API-Sending-custom-page-data-to-FullStory)
> expose setVars method on package interface

- .circleci/config.yml
Right now, deploys are triggered from the `main` branch. This is causing false negative build failures when merging dependabot PRs.
Some background:
GH-dependabot PRs get merged into `main`, but this triggers an NPM audit on `main` build, which fails the build since there are subsequent dependabot PRs that are yet to be merged.
Eventually, after all dependabot PRs are merged, the NPM audit passes but the `main` build can't go green because it is in a Hold state. At this point the only way it can go green is to do a full deploy to NPM.
But a full deploy to NPM should be unnecessary since these are only NPM audit fixes for dev deps.
This PR now only triggers the Hold + Deploy state when a version tag (`/v.*/`) is pushed to remote.
> hold and deploy steps will only execute when a version tag is pushed to remote

- README.md
- src/index.d.ts
- src/index.js
- test/index.js
This PR adds an `isInitialized` function which wraps `window._fs_initialized`. This is useful for code that could potentially repeatedly call `init` (like useEffects), leading to noisy console warnings. Checking for initialization before calling `init` would be helpful in this situation.
> Add isInitialized

- README.md
- src/index.d.ts
- src/index.js
This change provides a callback for logic that needs to run after a session has started. The callback is provided with the session URL since it's available from the 'start' event.
> Add a `ready` callback to the `init` function. Fixes #138

- src/index.d.ts
The existing `ReadyCallback` type is not valid TypeScript, resulting in a TS error when using the `@fullstory/browser` package.
This issue was introduced in v1.6.0.
This PR adjusts the type definition to be correct.
> Correctly define ReadyCallback parameter type

- .eslintrc
- src/index.js
- test/index.js
`fs.js` has been changed to remove debug logging, with a separate `fs-debug.js` provided for that purpose. As such, the snippet no longer honors the `_fs_debug` option. This change makes it so we load `fs-debug.js` when debug logging is requested.
> Support loading fs-debug.js when debug=true is passed in options. Fixes #150

- package-lock.json
- package.json
a recent pr updated our internal dependencies on webpack but not the dev dependency in the package.json file. this was causing dependabot and snyk automated pr's to have issues. this PR is an attempt to resolve this problem manually.
[valor ticket](https://fullstory.atlassian.net/browse/VAL-7460)
recent PR: https://github.com/fullstorydev/fullstory-browser-sdk/commit/d0c8290c65f54f5de2fdf6484cfb8fb5f6b10455
failed snyk request: https://github.com/fullstorydev/fullstory-browser-sdk/pull/167
failed dependabot request: https://github.com/fullstorydev/fullstory-browser-sdk/pull/168
> update internal dependency for webpack

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
For some reason, I thought I'd done this with the first beta release. I need to link to this (esp the upgrading section) in the beta release dev docs.
There are a couple of options here. We could either:
- Merge with a disclaimer at the top that this is the beta README and to go to `<insert link>` for version one.
- Keep this on a branch. Looks like I can still [deep link](https://github.com/fullstorydev/fullstory-browser-sdk/blob/scottnorvell/v2-readme-updates/README.md#migrating-to-version-200) to the README from the branch and it is available to the public. (at least an incognito window)
Thoughts on the above?
> updates to README for v2.0.0
