- README.md
> adding WIP warning

- src/index.js
- src/snippet.js
I'm separating the snippet into its own module in advance of some additional work around deployment.
> separating snippet into its own module

- .babelrc
- package-lock.json
- package.json
- rollup.config.js
A few things:
- I've cleaned up package dependancies
- I'm building with rollup.js to concatenate `import`s and output ES modules
- I've reduced the babel config to use only what I need
> adding rollup.js builder

- rollup.config.js
Hey Tim,
Would you please stamp this when you have a minute?
> updating rollup output to 'esm'

- README.md
Hey Ian and Van,
I updated the readme with a link to our API docs.
> Adding api reference link to readme

- .github/workflows/main.yml
- README.md
Testing the sync-snippet github action against the FS API staging endpoint
> test against staging snippet API endpoint

- package.json
- src/index.js
- test/index.js
Per Craig's suggestion: get rid of all that destructuring and make the code lesser :)
> refactor export statements

- README.md
- package.json
Adding yarn installation instructions and keywords to package.json. This is a patch version bump.
> adding yarn installation instructions and keywords to package.json

- CHANGELOG.md
- MAINTAINERS.json
I've added a `CHANGELOG.md` file and updated the `MAINTAINERS.json` file.
> changelog and maintainers updates

- CHANGELOG.md
- package-lock.json
- package.json
update version prior to npm deployment
> version bump + changelog update

- CHANGELOG.md
- package-lock.json
- package.json
I forgot to do this on the latest feature branch before I merged it :/
> version bump

- CHANGELOG.md
Whoops forgot about this in my last PR
> updating changelog to inlcude v1.4.5

- README.md
add Vue3 support via ~~[provide/inject](https://v3.vuejs.org/guide/component-provide-inject.html)~~  [global API](https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties) to read me
> vue3 support

- .circleci/config.yml
I've created a main branch
edit circle ci job to run deployment on `main` branch
> move circle ci deployment branch to main

- .circleci/config.yml
merge ci change into main branch
> move ci branch to main (#98)

- CHANGELOG.md
- package-lock.json
- package.json
- add 1.6.0 to changelog
- Release version 1.6.0
> release 1.6.0

- CHANGELOG.md
- package-lock.json
- package.json
- update changelog for 1.6.1
- Release version 1.6.1
> prepare release 1.6.1

- CHANGELOG.md
- package-lock.json
- package.json
- update changelog for 1.6.2
- Release version 1.6.2
> prepare release 1.6.2

- package-lock.json
> fixing two high vulnerabilities

- CHANGELOG.md
- package-lock.json
- package.json
Update to version 1.7.1 to be tagged and deployed after merging
> bump version

- CHANGELOG.md
- package-lock.json
- package.json
> Sabrina/2.0.0 beta.0

- CHANGELOG.md
Seems like my editor also stripped some whitespace 🤷
> updates changelog for v2.0.0-beta.3

- .circleci/config.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/index.ts
Releases @fullstory/browser@2.0.0
> Finalize version 2.0.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.test.ts
plus _maybe_ add additional tests for type safety if they actually pass 🤷
> bump @fullstory/snippet

- .circleci/config.yml
- CHANGELOG.md
- LICENSE
- README.md
- package-lock.json
- package.json
Making changes to adhere to our new brand guidelines
> Changing Fullstory casing in copy and KB URLs

- CHANGELOG.md
- package-lock.json
- package.json
bump @fullstory/snippet -> 2.0.5
> V2.0.6 release
